/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bead-three.glb 
Author: Ålands museum in The Aland islands, Finland (https://sketchfab.com/alandsmuseum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glass-bead-glasparla-fcd1007ce78e46d3974d6c9e70a288b5
Title: Glass bead - Glaspärla
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}bead-three.glb`
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.model_Material_u1_v1}
        position={[1.059, 18.514, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}bead-three.glb`);
