/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bead-one.glb 
Author: Igor Denisov (https://sketchfab.com/Digor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bead-i1k11b2sk3n54-2ca86cd496414814b6b084f2168ba109
Title: Bead I1K11B2Sk3N54
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}bead-one.glb`
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2.254, 1.409, 0.69]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bs_55} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Bs_55} />
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}bead-one.glb`);
