/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coffee.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import Marker from "./Marker";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/coffee.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0, 0, 0.085]} scale={0.085}>
            <mesh
              geometry={nodes.Coffee_Cup_Coffee_Cup_MAT_0.geometry}
              material={materials.Coffee_Cup_MAT}
            />
            <mesh
              geometry={nodes.Coffee_Coffee_Rosetta_Latte_MAT_0.geometry}
              material={materials.Coffee_Rosetta_Latte_MAT}
              scale={11.834}
            />
          </group>
          <mesh
            geometry={nodes.Cup_Plate_Coffee_Plate_MAT_0.geometry}
            material={materials.Coffee_Plate_MAT}
          />
          <Marker position={[0.08, 0.08, 0.13]} label="Iced Americano" />
          <Marker position={[1, 0.5, 1]} label="Handle" />
          <Marker position={[0, -0.2, 0]} label="Plate" />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/coffee.glb");
